name: 'Aj github action'
description: 'Aj sample gh action'
inputs:
  gh-token:
    required: false
    description: 'yes'
    default: ${{ github.token }}
  reviewer-count:
    description: 'How many per team'
    required: false
    default: '0'
outputs:
  result:
    description: 'The result'
runs:
  using: 'node16'
  main: 'index.js'